#!/usr/bin/env python3
"""
QUAD Documentation Generator
=============================

Generate industry-standard documentation for projects.

Usage:
  quad doc init                 # Initialize doc structure
  quad doc generate api         # Generate API docs
  quad doc generate db          # Generate DB docs
  quad doc generate arch        # Generate architecture docs
  quad doc generate journey     # Generate test journey
  quad doc generate all         # Generate all docs
  quad doc validate             # Validate doc structure
  quad doc config show          # Show doc config

Copyright (c) 2026 Gopi Suman Addanke. All Rights Reserved.
"""

import sys
import os
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional


class Console:
    """Simple console utilities"""

    @staticmethod
    def header(text: str):
        print(f"\n  {text}")
        print(f"  {'─' * len(text)}\n")

    @staticmethod
    def success(text: str):
        print(f"  ✓ {text}")

    @staticmethod
    def info(text: str):
        print(f"  → {text}")

    @staticmethod
    def error(text: str):
        print(f"  ✗ {text}")

    @staticmethod
    def warn(text: str):
        print(f"  ⚠ {text}")


def find_project_root() -> Optional[Path]:
    """Find project root by looking for .quad/ folder"""
    cwd = Path.cwd()
    for parent in [cwd] + list(cwd.parents):
        quad_dir = parent / ".quad"
        if quad_dir.exists():
            return parent
    return None


def load_doc_config() -> Dict:
    """Load documentation configuration"""
    # Check project-level config first
    project_root = find_project_root()
    if project_root:
        config_file = project_root / ".quad" / "doc-config.json"
        if config_file.exists():
            return json.loads(config_file.read_text())

    # Check QUAD framework config
    quad_root = Path(__file__).parent.parent.parent.parent
    config_file = quad_root / ".quad" / "doc-config.json"
    if config_file.exists():
        return json.loads(config_file.read_text())

    # Default config
    return {
        "documentation_root": "documentation",
        "structure": {
            "architecture": "documentation/architecture",
            "api": "documentation/api",
            "database": "documentation/database",
            "testing": "documentation/testing",
            "deployment": "documentation/deployment",
            "security": "documentation/security",
            "misc": "documentation/misc"
        }
    }


def get_doc_path(category: str) -> Path:
    """Get documentation path for category"""
    config = load_doc_config()
    project_root = find_project_root() or Path.cwd()

    category_path = config.get("structure", {}).get(
        category,
        f"{config['documentation_root']}/{category}"
    )

    return project_root / category_path


def init_documentation():
    """Initialize documentation structure"""
    Console.header("Initialize Documentation Structure")

    config = load_doc_config()
    project_root = find_project_root() or Path.cwd()

    Console.info(f"Project: {project_root.name}")

    # Create all category folders
    created = 0
    for category, path in config.get("structure", {}).items():
        full_path = project_root / path
        if not full_path.exists():
            full_path.mkdir(parents=True, exist_ok=True)

            # Create README.md in each folder
            readme_path = full_path / "README.md"
            readme_content = f"""# {category.title()} Documentation

## Overview

{category.title()} documentation for {project_root.name}.

## Contents

*Documentation files will appear here as they are generated.*

---

*Generated by QUAD on {datetime.now().strftime('%Y-%m-%d')}*
"""
            readme_path.write_text(readme_content)
            Console.success(f"Created: {path}/")
            created += 1

    # Create main documentation index
    doc_root = project_root / config["documentation_root"]
    index_path = doc_root / "README.md"

    if not index_path.exists():
        index_content = f"""# {project_root.name} Documentation

**Generated:** {datetime.now().strftime('%Y-%m-%d')}

---

## Documentation Categories

"""
        for category in config.get("structure", {}).keys():
            index_content += f"- [{category.title()}]({category}/README.md)\n"

        index_content += """
---

## Quick Links

- [Architecture Overview](architecture/README.md)
- [API Reference](api/README.md)
- [Database Schema](database/README.md)
- [Test Journeys](testing/README.md)

---

*Generated by QUAD*
"""
        index_path.write_text(index_content)
        Console.success("Created: documentation/README.md")
        created += 1

    print()
    if created > 0:
        Console.success(f"Documentation structure initialized! ({created} files created)")
    else:
        Console.info("Documentation structure already exists")


def generate_api_docs():
    """Generate API documentation"""
    Console.header("Generate API Documentation")

    api_path = get_doc_path("api")
    api_path.mkdir(parents=True, exist_ok=True)

    # TODO: Implement actual API doc generation
    Console.warn("API doc generation not yet implemented")
    Console.info("Coming in Phase 2")
    Console.info("")
    Console.info("Will generate:")
    Console.info("  - API-REFERENCE.md")
    Console.info("  - endpoints/*.md")
    Console.info("  - swagger.yaml")


def generate_db_docs():
    """Generate database documentation"""
    Console.header("Generate Database Documentation")

    db_path = get_doc_path("database")
    db_path.mkdir(parents=True, exist_ok=True)

    # TODO: Implement actual DB doc generation
    Console.warn("Database doc generation not yet implemented")
    Console.info("Coming in Phase 2")
    Console.info("")
    Console.info("Will generate:")
    Console.info("  - SCHEMA.md")
    Console.info("  - schema.sql")
    Console.info("  - tables/*.md")
    Console.info("  - erd.png")


def generate_arch_docs():
    """Generate architecture documentation"""
    Console.header("Generate Architecture Documentation")

    arch_path = get_doc_path("architecture")
    arch_path.mkdir(parents=True, exist_ok=True)

    project_root = find_project_root() or Path.cwd()

    # Load project config
    config_file = project_root / ".quad" / "config.json"
    if config_file.exists():
        project_config = json.loads(config_file.read_text())
    else:
        Console.error("No project config found. Run: quad init <project-name>")
        return

    # Generate architecture doc
    arch_file = arch_path / "SYSTEM-ARCHITECTURE.md"

    project_name = project_config.get("project_name", "Project")
    project_type = project_config.get("project_type", "fullstack")
    frontend = project_config.get("frontend", "none")
    backend = project_config.get("backend", "none")
    database = project_config.get("database", "none")

    arch_content = f"""# System Architecture: {project_name}

**Generated:** {datetime.now().strftime('%Y-%m-%d')}
**Project Type:** {project_type}

---

## Overview

{project_name} is a {project_type} application built using the QUAD methodology.

## Technology Stack

### Frontend
- **Framework:** {frontend.title() if frontend != 'none' else 'N/A'}
- **Language:** TypeScript
- **Styling:** Tailwind CSS
- **State Management:** Zustand
- **HTTP Client:** Fetch API / React Query

### Backend
- **Framework:** {backend.title() if backend != 'none' else 'N/A'}
- **Language:** {'Java' if backend == 'springboot' else 'TypeScript' if backend == 'nodejs' else 'Python' if backend == 'python' else 'N/A'}
- **Database:** {database.title()}
- **Authentication:** JWT

### Infrastructure
- **Hosting:** TBD
- **CI/CD:** GitHub Actions
- **Monitoring:** TBD

---

## System Context Diagram

```
[Users] → [Web App] → [API Server] → [Database]
                           ↓
                    [External Services]
```

---

## Component Diagram

### Frontend Components
```
{project_name}-web/
├── app/                  # Next.js pages
├── components/           # React components
├── lib/                  # Utilities
└── api/                  # API client
```

### Backend Components
```
{project_name}-api/
├── controllers/          # REST endpoints
├── services/             # Business logic
├── repositories/         # Data access
└── models/               # Entities
```

---

## Data Flow

1. User interacts with web interface
2. Frontend sends API request
3. Backend validates and processes
4. Database query executed
5. Response returned to frontend
6. UI updates with result

---

## Security

### Authentication
- JWT-based authentication
- Token expiration: 24 hours
- Refresh token support

### Authorization
- Role-based access control (RBAC)
- Permission checks at API level

---

## Deployment

### Environments
- **Development:** Local development
- **Staging:** Pre-production testing
- **Production:** Live environment

---

## Architecture Decisions

### ADR-001: Technology Stack
**Status:** Accepted
**Date:** {datetime.now().strftime('%Y-%m-%d')}

**Context:**
Need to choose technology stack for {project_type} application.

**Decision:**
- Frontend: {frontend.title()}
- Backend: {backend.title()}
- Database: {database.title()}

**Consequences:**
- Proven enterprise frameworks
- Strong community support
- Good developer experience

---

*Generated by QUAD*
"""

    arch_file.write_text(arch_content)
    Console.success(f"Created: {arch_file.relative_to(project_root)}")


def generate_test_journey():
    """Generate test journey template"""
    Console.header("Generate Test Journey")

    test_path = get_doc_path("testing")
    test_path.mkdir(parents=True, exist_ok=True)

    # Create test-journeys subfolder
    journeys_path = test_path / "test-journeys"
    journeys_path.mkdir(parents=True, exist_ok=True)

    # Generate sample journey
    journey_file = journeys_path / "SAMPLE-JOURNEY.md"

    journey_content = """# Test Journey: Sample Feature

## Metadata
- **ID:** TJ-001
- **Feature:** Sample Feature
- **Story:** As a user, I can perform sample action
- **Priority:** P1
- **Status:** Draft

## Overview
This is a sample test journey demonstrating the format.

## Prerequisites
- [ ] Application running
- [ ] Test data loaded
- [ ] User authenticated

---

## Test Steps

### Step 1: Navigate to Feature
**Action:**
Navigate to the feature page.

**Expected Result:**
Feature page loads successfully.

**APIs Called:**
- `GET /api/v1/feature`
  - Response: `{"data": [...]}`
  - Status: 200 OK

**Database Impact:**
| Table | Operation | Rows Affected |
|-------|-----------|---------------|
| features | SELECT | Multiple |

---

### Step 2: Perform Action
**Action:**
Click action button.

**Expected Result:**
Action completes successfully.

**APIs Called:**
- `POST /api/v1/feature/action`
  - Request: `{"param": "value"}`
  - Response: `{"success": true}`
  - Status: 200 OK

**Database Impact:**
| Table | Operation | Rows Affected |
|-------|-----------|---------------|
| features | UPDATE | 1 |
| audit_log | INSERT | 1 |

---

## Database Impact Summary

| Table | Operations | Fields Touched |
|-------|------------|----------------|
| features | SELECT, UPDATE | id, name, status |
| audit_log | INSERT | id, action, timestamp |

## API Call Summary

| Endpoint | Method | Purpose | Response Time |
|----------|--------|---------|---------------|
| /api/v1/feature | GET | Load data | <200ms |
| /api/v1/feature/action | POST | Perform action | <500ms |

## Flow Diagram

```
[User] → [Feature Page] → [GET /feature] → [Display Data]
          ↓
       [Click Action] → [POST /action] → [Update DB] → [Success]
```

## Error Scenarios

1. **Invalid Input**
   - Input: Invalid parameters
   - Expected: 400 Bad Request
   - Message: "Invalid input"

2. **Unauthorized**
   - Input: No auth token
   - Expected: 401 Unauthorized
   - Message: "Authentication required"

## Performance Benchmarks
- **Target:** <500ms end-to-end
- **Acceptable:** <1s
- **Unacceptable:** >1s

## Dependencies
- Story: US-001 (Sample Story)
- APIs: Feature Service
- Tables: features, audit_log

## Notes
This is a template. Customize for your specific test scenarios.

---

*Generated by QUAD*
"""

    journey_file.write_text(journey_content)
    Console.success(f"Created: {journey_file.relative_to(find_project_root() or Path.cwd())}")


def generate_all_docs():
    """Generate all documentation"""
    Console.header("Generate All Documentation")

    generate_arch_docs()
    print()
    generate_api_docs()
    print()
    generate_db_docs()
    print()
    generate_test_journey()

    print()
    Console.success("Documentation generation complete!")


def validate_docs():
    """Validate documentation structure"""
    Console.header("Validate Documentation")

    config = load_doc_config()
    project_root = find_project_root() or Path.cwd()

    checks_passed = 0
    checks_failed = 0

    # Check 1: Documentation root exists
    doc_root = project_root / config["documentation_root"]
    if doc_root.exists():
        Console.success(f"Documentation root exists: {config['documentation_root']}/")
        checks_passed += 1
    else:
        Console.error(f"Documentation root missing: {config['documentation_root']}/")
        checks_failed += 1

    # Check 2: Required folders exist
    for category, path in config.get("structure", {}).items():
        full_path = project_root / path
        if full_path.exists():
            checks_passed += 1

            # Check for README.md
            readme_path = full_path / "README.md"
            if readme_path.exists():
                checks_passed += 1
            else:
                Console.warn(f"Missing README.md in: {path}/")
                checks_failed += 1
        else:
            Console.error(f"Missing folder: {path}/")
            checks_failed += 1

    # Summary
    print()
    total = checks_passed + checks_failed
    score = int((checks_passed / total) * 100) if total > 0 else 0

    if score == 100:
        Console.success(f"All checks passed! Score: {score}%")
    elif score >= 80:
        Console.info(f"Most checks passed. Score: {score}%")
    else:
        Console.warn(f"Several checks failed. Score: {score}%")

    print()
    Console.info(f"Passed: {checks_passed}/{total}")
    Console.info(f"Failed: {checks_failed}/{total}")


def show_config():
    """Show documentation configuration"""
    Console.header("Documentation Configuration")

    config = load_doc_config()

    print(f"  Documentation Root: {config['documentation_root']}")
    print()
    print("  Categories:")
    for category, path in config.get("structure", {}).items():
        print(f"    {category:20} → {path}")
    print()

    if "templates" in config:
        print("  Templates:")
        print(f"    QUAD Defaults:  {config['templates'].get('quad_defaults', 'N/A')}")
        print(f"    Org Templates:  {config['templates'].get('org_templates', 'N/A')}")
        print(f"    Project:        {config['templates'].get('project_templates', 'N/A')}")


def run_doc(subcommand: str = None, args: List[str] = None):
    """Entry point for CLI integration"""
    args = args or []

    if subcommand == "init":
        init_documentation()

    elif subcommand == "generate":
        if not args:
            Console.error("Specify what to generate: api, db, arch, journey, all")
            return

        target = args[0]
        if target == "api":
            generate_api_docs()
        elif target == "db":
            generate_db_docs()
        elif target == "arch":
            generate_arch_docs()
        elif target == "journey":
            generate_test_journey()
        elif target == "all":
            generate_all_docs()
        else:
            Console.error(f"Unknown target: {target}")

    elif subcommand == "validate":
        validate_docs()

    elif subcommand == "config":
        if args and args[0] == "show":
            show_config()
        else:
            show_config()

    else:
        Console.header("QUAD Documentation Commands")
        Console.info("quad doc init                 - Initialize doc structure")
        Console.info("quad doc generate arch        - Generate architecture docs")
        Console.info("quad doc generate api         - Generate API docs")
        Console.info("quad doc generate db          - Generate DB docs")
        Console.info("quad doc generate journey     - Generate test journey")
        Console.info("quad doc generate all         - Generate all docs")
        Console.info("quad doc validate             - Validate doc structure")
        Console.info("quad doc config show          - Show doc config")
        print()


def main():
    """Command-line entry point"""
    args = sys.argv[1:]

    if not args or args[0] in ("-h", "--help"):
        run_doc("help")
    else:
        run_doc(args[0], args[1:])


if __name__ == "__main__":
    main()
