#!/bin/bash

# QUAD Framework - Developer Environment Setup
# Purpose: Set up a new developer machine with secrets from Vaultwarden
# Usage: ./scripts/setup-dev-environment.sh

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔═══════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   QUAD Framework - Developer Environment Setup   ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════╝${NC}"
echo ""

# Check if Bitwarden CLI is installed
if ! command -v bw &> /dev/null; then
    echo -e "${RED}❌ Bitwarden CLI not installed${NC}"
    echo -e "${YELLOW}Install with: brew install bitwarden-cli${NC}"
    exit 1
fi

# Check if logged in to Vaultwarden
if ! bw login --check &> /dev/null; then
    echo -e "${YELLOW}🔐 Not logged in to Vaultwarden${NC}"
    echo -e "${BLUE}Login with: bw config server https://vault.nutrinine.app && bw login${NC}"
    exit 1
fi

# Check if vault is unlocked
if ! bw unlock --check &> /dev/null; then
    echo -e "${YELLOW}🔓 Vault is locked${NC}"
    echo -e "${BLUE}Run: export BW_SESSION=\$(bw unlock --raw)${NC}"
    exit 1
fi

# Check BW_SESSION is set
if [ -z "$BW_SESSION" ]; then
    echo -e "${YELLOW}⚠️  BW_SESSION not set${NC}"
    echo -e "${BLUE}Run: export BW_SESSION=\$(bw unlock --raw)${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Vaultwarden connection verified${NC}"
echo ""

# QUAD Organization ID
QUAD_ORG_ID="579c22f3-4f13-447c-a861-9a4aa0ab7fbc"
DEV_COLLECTION_ID="e4f03d1a-b8ac-4186-a384-0fb62d431ddd"
QA_COLLECTION_ID="75fb3b57-9e84-4e2d-8b4f-447518e0a315"

echo -e "${BLUE}📥 Fetching credentials from Vaultwarden...${NC}"
echo ""

# Function to get field value from vault item
get_vault_field() {
    local item_name=$1
    local field_name=$2
    local collection_id=$3

    bw get item "$item_name" --organizationid $QUAD_ORG_ID 2>/dev/null | \
        jq -r ".fields[] | select(.name==\"$field_name\") | .value" 2>/dev/null || echo ""
}

# Function to get username/password from vault item
get_vault_login() {
    local item_name=$1
    local field=$2  # "username" or "password"

    bw get item "$item_name" --organizationid $QUAD_ORG_ID 2>/dev/null | \
        jq -r ".login.$field" 2>/dev/null || echo ""
}

# Create .env.local for quad-web
echo -e "${BLUE}Creating quad-web/.env.local...${NC}"

# Fetch Database credentials
DB_HOST=$(get_vault_field "Database" "DB_HOST" $DEV_COLLECTION_ID)
DB_PORT=$(get_vault_field "Database" "DB_PORT" $DEV_COLLECTION_ID)
DB_NAME=$(get_vault_field "Database" "DB_NAME" $DEV_COLLECTION_ID)
DB_USER=$(get_vault_field "Database" "DB_USER" $DEV_COLLECTION_ID)
DB_PASSWORD=$(get_vault_field "Database" "DB_PASSWORD" $DEV_COLLECTION_ID)

# Fetch Google OAuth
GOOGLE_CLIENT_ID=$(get_vault_field "Google OAuth" "GOOGLE_CLIENT_ID" $DEV_COLLECTION_ID)
GOOGLE_CLIENT_SECRET=$(get_vault_field "Google OAuth" "GOOGLE_CLIENT_SECRET" $DEV_COLLECTION_ID)

# Fetch GitHub OAuth
GITHUB_CLIENT_ID=$(get_vault_field "GitHub OAuth" "GITHUB_CLIENT_ID" $DEV_COLLECTION_ID)
GITHUB_CLIENT_SECRET=$(get_vault_field "GitHub OAuth" "GITHUB_CLIENT_SECRET" $DEV_COLLECTION_ID)

# Fetch NextAuth Secret
NEXTAUTH_SECRET=$(get_vault_field "NextAuth Secret" "NEXTAUTH_SECRET" $DEV_COLLECTION_ID)

# Fetch Anthropic API Key
ANTHROPIC_API_KEY=$(get_vault_field "Anthropic API Key" "ANTHROPIC_API_KEY" $DEV_COLLECTION_ID)

# Generate DATABASE_URL
DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"

# Write .env.local file
cat > quad-web/.env.local << EOF
# QUAD Framework - Development Environment
# Generated by setup-dev-environment.sh on $(date)
# DO NOT COMMIT THIS FILE TO GIT

# Database Configuration
DB_HOST=${DB_HOST:-postgres-quad-dev}
DB_PORT=${DB_PORT:-5432}
DB_NAME=${DB_NAME:-quad_dev_db}
DB_USER=${DB_USER:-quad_user}
DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=${DATABASE_URL}

# NextAuth Configuration
NEXTAUTH_URL=http://localhost:14001
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# OAuth Providers
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}

# AI Configuration
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# Email Configuration (optional for local dev)
EMAIL_PROVIDER=console
EMAIL_FROM=QUAD Platform <noreply@quadframe.work>
EOF

echo -e "${GREEN}✅ quad-web/.env.local created${NC}"
echo ""

# Create .env.deploy for deployment scripts
echo -e "${BLUE}Creating .env.deploy...${NC}"

cat > .env.deploy << EOF
# QUAD Framework - Deployment Secrets
# Generated by setup-dev-environment.sh on $(date)
# DO NOT COMMIT THIS FILE TO GIT

# DEV Environment
DEV_DB_HOST=${DB_HOST:-postgres-quad-dev}
DEV_DB_NAME=${DB_NAME:-quad_dev_db}
DEV_DB_PASS=${DB_PASSWORD}
DEV_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
DEV_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
DEV_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
DEV_GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
DEV_NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
DEV_ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# QA Environment (TODO: Add QA credentials from vault)
QA_DB_HOST=postgres-quad-qa
QA_DB_NAME=quad_qa_db
QA_DB_PASS=<fetch from vault QA collection>

# Shared
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
EOF

echo -e "${GREEN}✅ .env.deploy created${NC}"
echo ""

# Verify .gitignore
echo -e "${BLUE}Verifying .gitignore...${NC}"

if ! grep -q ".env.local" quad-web/.gitignore 2>/dev/null; then
    echo ".env.local" >> quad-web/.gitignore
    echo -e "${YELLOW}⚠️  Added .env.local to quad-web/.gitignore${NC}"
fi

if ! grep -q ".env.deploy" .gitignore 2>/dev/null; then
    echo ".env.deploy" >> .gitignore
    echo -e "${YELLOW}⚠️  Added .env.deploy to .gitignore${NC}"
fi

echo -e "${GREEN}✅ .gitignore updated${NC}"
echo ""

# Summary
echo -e "${BLUE}╔═══════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║              Setup Complete! ✅                    ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}Files created:${NC}"
echo -e "  ✅ quad-web/.env.local (for local development)"
echo -e "  ✅ .env.deploy (for deployment scripts)"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo -e "  1. cd quad-web && npm install"
echo -e "  2. npm run dev (starts on port 14001)"
echo -e "  3. Visit: http://localhost:14001"
echo ""
echo -e "${YELLOW}To deploy to DEV/QA:${NC}"
echo -e "  ./deployment/scripts/deploy-studio.sh dev"
echo ""
